/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 08-oct.-2022 16:36:17 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `Aeropuerto` CASCADE
;

DROP TABLE IF EXISTS `AgenciaViajes` CASCADE
;

DROP TABLE IF EXISTS `Alojamiento` CASCADE
;

DROP TABLE IF EXISTS `Asiento` CASCADE
;

DROP TABLE IF EXISTS `Avion` CASCADE
;

DROP TABLE IF EXISTS `Caracteristica` CASCADE
;

DROP TABLE IF EXISTS `Ciudad` CASCADE
;

DROP TABLE IF EXISTS `Cliente` CASCADE
;

DROP TABLE IF EXISTS `Direccion` CASCADE
;

DROP TABLE IF EXISTS `EmpresaProveedora` CASCADE
;

DROP TABLE IF EXISTS `EmpresasNoBancaria` CASCADE
;

DROP TABLE IF EXISTS `LineaDePago` CASCADE
;

DROP TABLE IF EXISTS `MedioDePago` CASCADE
;

DROP TABLE IF EXISTS `Oferta` CASCADE
;

DROP TABLE IF EXISTS `Pago` CASCADE
;

DROP TABLE IF EXISTS `Pais` CASCADE
;

DROP TABLE IF EXISTS `PaqueteTuristico` CASCADE
;

DROP TABLE IF EXISTS `Region` CASCADE
;

DROP TABLE IF EXISTS `Reserva` CASCADE
;

DROP TABLE IF EXISTS `ServicioDelAlojamiento` CASCADE
;

DROP TABLE IF EXISTS `ServicioDePago` CASCADE
;

DROP TABLE IF EXISTS `Tarjeta` CASCADE
;

DROP TABLE IF EXISTS `TipoDeHabitación` CASCADE
;

DROP TABLE IF EXISTS `Transferencia` CASCADE
;

DROP TABLE IF EXISTS `Usuario` CASCADE
;

DROP TABLE IF EXISTS `Vehiculo` CASCADE
;

DROP TABLE IF EXISTS `Vuelo` CASCADE
;

/* Create Tables */

CREATE TABLE `Aeropuerto`
(
	`codigoIata` int 	 NULL,
	`latitud` double 	 NULL,
	`longitud` double 	 NULL,
	`nombre` char(0) 	 NULL,
	`aeropuertoID` Integer NOT NULL,
	`regionID` Integer 	 NULL,
	CONSTRAINT `PK_Aeropuerto` PRIMARY KEY (`aeropuertoID`)
)

;

CREATE TABLE `AgenciaViajes`
(
	`agenciaViajesID` Integer NOT NULL,
	CONSTRAINT `PK_AgenciaViajes` PRIMARY KEY (`agenciaViajesID`)
)

;

CREATE TABLE `Alojamiento`
(
	`categoria` int 	 NULL,
	`descripcion` char(0) 	 NULL,
	`horarioCheckIn` time(0) 	 NULL,
	`horarioCheckOut` time(0) 	 NULL,
	`latitud` double 	 NULL,
	`longitud` double 	 NULL,
	`nombre` char(0) 	 NULL,
	`alojamientoID` Integer NOT NULL,
	`paqueteTuristicoID` Integer 	 NULL,
	CONSTRAINT `PK_Alojamiento` PRIMARY KEY (`alojamientoID`)
)

;

CREATE TABLE `Asiento`
(
	`clase` Clase 	 NULL,
	`estado` EstadoAsiento 	 NULL,
	`numero` int 	 NULL,
	`asientoID` Integer NOT NULL,
	`avionID` Integer 	 NULL,
	CONSTRAINT `PK_Asiento` PRIMARY KEY (`asientoID`)
)

;

CREATE TABLE `Avion`
(
	`aerolinea` char(0) 	 NULL,
	`cantidadAsientos` int 	 NULL,
	`matricula` char(0) 	 NULL,
	`avionID` Integer NOT NULL,
	CONSTRAINT `PK_Avion` PRIMARY KEY (`avionID`)
)

;

CREATE TABLE `Caracteristica`
(
	`descripcion` char(0) 	 NULL,
	`nombre` char(0) 	 NULL,
	`caracteristicaID` Integer NOT NULL,
	`vehiculoID` Integer 	 NULL,
	CONSTRAINT `PK_Caracteristica` PRIMARY KEY (`caracteristicaID`)
)

;

CREATE TABLE `Ciudad`
(
	`codigoPostal` int 	 NULL,
	`nombre` char(0) 	 NULL,
	`ciudadID` Integer NOT NULL,
	`regionID` Integer 	 NULL,
	CONSTRAINT `PK_Ciudad` PRIMARY KEY (`ciudadID`)
)

;

CREATE TABLE `Cliente`
(
	`dni` int 	 NULL,
	`fechaNacimiento` date 	 NULL,
	`telefono` char(0) 	 NULL,
	`tipoDocumento` char(0) 	 NULL,
	`clienteID` Integer NOT NULL,
	CONSTRAINT `PK_Cliente` PRIMARY KEY (`clienteID`)
)

;

CREATE TABLE `Direccion`
(
	`altura` int 	 NULL,
	`calle` char(0) 	 NULL,
	`direccionID` Integer NOT NULL,
	`alojamientoID` Integer 	 NULL,
	`ciudadID` Integer 	 NULL,
	`clienteID` Integer 	 NULL,
	CONSTRAINT `PK_Direccion` PRIMARY KEY (`direccionID`)
)

;

CREATE TABLE `EmpresaProveedora`
(
	`calificacionPromedio` int 	 NULL,
	`nombre` char(0) 	 NULL,
	`empresaProveedoraID` Integer NOT NULL,
	CONSTRAINT `PK_EmpresaProveedora` PRIMARY KEY (`empresaProveedoraID`)
)

;

CREATE TABLE `EmpresasNoBancaria`
(
	`codigoBarras` int 	 NULL,
	`empresasNoBancariaID` Integer NOT NULL,
	CONSTRAINT `PK_EmpresasNoBancaria` PRIMARY KEY (`empresasNoBancariaID`)
)

;

CREATE TABLE `LineaDePago`
(
	`lineaDePagoID` Integer NOT NULL,
	`medioDePagoID` Integer 	 NULL,
	`pagoID` Integer 	 NULL,
	`servicioDePagoID` Integer 	 NULL,
	CONSTRAINT `PK_LineaDePago` PRIMARY KEY (`lineaDePagoID`)
)

;

CREATE TABLE `MedioDePago`
(
	`medioDePagoID` Integer NOT NULL,
	`lineaDePagoID` varchar(50) NOT NULL,
	CONSTRAINT `PK_MedioDePago` PRIMARY KEY (`medioDePagoID`)
)

;

CREATE TABLE `Oferta`
(
	`fechaFin` date 	 NULL,
	`fechaInicio` date 	 NULL,
	`ofertaID` Integer NOT NULL,
	CONSTRAINT `PK_Oferta` PRIMARY KEY (`ofertaID`)
)

;

CREATE TABLE `Pago`
(
	`monto` float(0) 	 NULL,
	`pagoID` Integer NOT NULL,
	`reservaID` Integer 	 NULL,
	CONSTRAINT `PK_Pago` PRIMARY KEY (`pagoID`)
)

;

CREATE TABLE `Pais`
(
	`nombre` char(0) 	 NULL,
	`paisID` Integer NOT NULL,
	CONSTRAINT `PK_Pais` PRIMARY KEY (`paisID`)
)

;

CREATE TABLE `PaqueteTuristico`
(
	`cantidadDias` int 	 NULL,
	`cantidadNoches` int 	 NULL,
	`descripcion` char(0) 	 NULL,
	`nombre` int 	 NULL,
	`paqueteTuristicoID` Integer NOT NULL,
	CONSTRAINT `PK_PaqueteTuristico` PRIMARY KEY (`paqueteTuristicoID`)
)

;

CREATE TABLE `Region`
(
	`nombre` char(0) 	 NULL,
	`regionID` Integer NOT NULL,
	`paisID` Integer 	 NULL,
	CONSTRAINT `PK_Region` PRIMARY KEY (`regionID`)
)

;

CREATE TABLE `Reserva`
(
	`estado` EstadoReserva 	 NULL,
	`reservaID` Integer NOT NULL,
	`clienteID` Integer 	 NULL,
	CONSTRAINT `PK_Reserva` PRIMARY KEY (`reservaID`)
)

;

CREATE TABLE `ServicioDelAlojamiento`
(
	`descripcion` char(0) 	 NULL,
	`nombre` char(0) 	 NULL,
	`servicioDelAlojamientoID` Integer NOT NULL,
	`alojamientoID` Integer 	 NULL,
	CONSTRAINT `PK_ServicioDelAlojamiento` PRIMARY KEY (`servicioDelAlojamientoID`)
)

;

CREATE TABLE `ServicioDePago`
(
	`nombre` char(0) 	 NULL,
	`servicioDePagoID` Integer NOT NULL,
	`lineaDePagoID` Integer 	 NULL,
	CONSTRAINT `PK_ServicioDePago` PRIMARY KEY (`servicioDePagoID`)
)

;

CREATE TABLE `Tarjeta`
(
	`utimosNumerosTarjeta` int 	 NULL,
	`tarjetaID` Integer NOT NULL,
	CONSTRAINT `PK_Tarjeta` PRIMARY KEY (`tarjetaID`)
)

;

CREATE TABLE `TipoDeHabitación`
(
	`capacidad` int 	 NULL,
	`descripcion` char(0) 	 NULL,
	`nombre` char(0) 	 NULL,
	`precioPorNoche` float(0) 	 NULL,
	`tipoDeHabitaciónID` Integer NOT NULL,
	`alojamientoID` Integer 	 NULL,
	CONSTRAINT `PK_TipoDeHabitación` PRIMARY KEY (`tipoDeHabitaciónID`)
)

;

CREATE TABLE `Transferencia`
(
	`cvu` int 	 NULL,
	`transferenciaID` Integer NOT NULL,
	CONSTRAINT `PK_Transferencia` PRIMARY KEY (`transferenciaID`)
)

;

CREATE TABLE `Usuario`
(
	`apellido` char(0) 	 NULL,
	`correoElectronico` char(0) 	 NULL,
	`nombre` char(0) 	 NULL,
	`rol` Rol 	 NULL,
	`usuarioID` Integer NOT NULL,
	`agenciaViajesID` Integer 	 NULL,
	CONSTRAINT `PK_Usuario` PRIMARY KEY (`usuarioID`)
)

;

CREATE TABLE `Vehiculo`
(
	`marca` char(0) 	 NULL,
	`modelo` char(0) 	 NULL,
	`nombre` char(0) 	 NULL,
	`precio` float(0) 	 NULL,
	`vehiculoID` Integer NOT NULL,
	`empresaProveedoraID` Integer 	 NULL,
	`paqueteTuristicoID` Integer 	 NULL,
	CONSTRAINT `PK_Vehiculo` PRIMARY KEY (`vehiculoID`)
)

;

CREATE TABLE `Vuelo`
(
	`aeropuertoDestino` Aeropuerto 	 NULL,
	`aeropuertoOrigen` Aeropuerto 	 NULL,
	`fechaYHoraArribo` datetime(0) 	 NULL,
	`fechaYHoraPartida` datetime(0) 	 NULL,
	`precio` float(0) 	 NULL,
	`vueloID` Integer NOT NULL,
	`avionID` Integer 	 NULL,
	`ofertaID` Integer 	 NULL,
	`paqueteTuristicoID` Integer 	 NULL,
	CONSTRAINT `PK_Vuelo` PRIMARY KEY (`vueloID`)
)

;

/* Create Indexes, Uniques, Checks */

ALTER TABLE `LineaDePago` 
 ADD INDEX `IXFK_LineaDePago_MedioDePago` (`medioDePagoID` ASC)
;

ALTER TABLE `LineaDePago` 
 ADD INDEX `IXFK_LineaDePago_ServicioDePago` (`servicioDePagoID` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Aeropuerto` 
 ADD CONSTRAINT `FK_Aeropuerto_Region`
	FOREIGN KEY (`regionID`) REFERENCES `Region` (`regionID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Alojamiento` 
 ADD CONSTRAINT `FK_Alojamiento_PaqueteTuristico`
	FOREIGN KEY (`paqueteTuristicoID`) REFERENCES `PaqueteTuristico` (`paqueteTuristicoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Asiento` 
 ADD CONSTRAINT `FK_Asiento_Avion`
	FOREIGN KEY (`avionID`) REFERENCES `Avion` (`avionID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Caracteristica` 
 ADD CONSTRAINT `FK_Caracteristica_Vehiculo`
	FOREIGN KEY (`vehiculoID`) REFERENCES `Vehiculo` (`vehiculoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Ciudad` 
 ADD CONSTRAINT `FK_Ciudad_Region`
	FOREIGN KEY (`regionID`) REFERENCES `Region` (`regionID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Cliente` 
 ADD CONSTRAINT `FK_Cliente_Usuario`
	FOREIGN KEY (`clienteID`) REFERENCES `Usuario` (`usuarioID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Direccion` 
 ADD CONSTRAINT `FK_Direccion_Alojamiento`
	FOREIGN KEY (`alojamientoID`) REFERENCES `Alojamiento` (`alojamientoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Direccion` 
 ADD CONSTRAINT `FK_Direccion_Ciudad`
	FOREIGN KEY (`ciudadID`) REFERENCES `Ciudad` (`ciudadID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Direccion` 
 ADD CONSTRAINT `FK_Direccion_Cliente`
	FOREIGN KEY (`clienteID`) REFERENCES `Cliente` (`clienteID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `EmpresasNoBancaria` 
 ADD CONSTRAINT `FK_EmpresasNoBancaria_MedioDePago`
	FOREIGN KEY (`empresasNoBancariaID`) REFERENCES `MedioDePago` (`medioDePagoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `LineaDePago` 
 ADD CONSTRAINT `FK_LineaDePago_ServicioDePago`
	FOREIGN KEY (`servicioDePagoID`) REFERENCES `ServicioDePago` (`servicioDePagoID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `LineaDePago` 
 ADD CONSTRAINT `FK_LineaDePago_Pago`
	FOREIGN KEY (`pagoID`) REFERENCES `Pago` (`pagoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MedioDePago` 
 ADD CONSTRAINT `FK_LineaDePago`
	FOREIGN KEY () REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Pago` 
 ADD CONSTRAINT `FK_Pago_Reserva`
	FOREIGN KEY (`reservaID`) REFERENCES `Reserva` (`reservaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Region` 
 ADD CONSTRAINT `FK_Region_Pais`
	FOREIGN KEY (`paisID`) REFERENCES `Pais` (`paisID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Reserva` 
 ADD CONSTRAINT `FK_Reserva_Cliente`
	FOREIGN KEY (`clienteID`) REFERENCES `Cliente` (`clienteID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ServicioDelAlojamiento` 
 ADD CONSTRAINT `FK_ServicioDelAlojamiento_Alojamiento`
	FOREIGN KEY (`alojamientoID`) REFERENCES `Alojamiento` (`alojamientoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Tarjeta` 
 ADD CONSTRAINT `FK_Tarjeta_MedioDePago`
	FOREIGN KEY (`tarjetaID`) REFERENCES `MedioDePago` (`medioDePagoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `TipoDeHabitación` 
 ADD CONSTRAINT `FK_TipoDeHabitación_Alojamiento`
	FOREIGN KEY (`alojamientoID`) REFERENCES `Alojamiento` (`alojamientoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Transferencia` 
 ADD CONSTRAINT `FK_Transferencia_MedioDePago`
	FOREIGN KEY (`transferenciaID`) REFERENCES `MedioDePago` (`medioDePagoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Usuario` 
 ADD CONSTRAINT `FK_Usuario_AgenciaViajes`
	FOREIGN KEY (`agenciaViajesID`) REFERENCES `AgenciaViajes` (`agenciaViajesID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Vehiculo` 
 ADD CONSTRAINT `FK_Vehiculo_EmpresaProveedora`
	FOREIGN KEY (`empresaProveedoraID`) REFERENCES `EmpresaProveedora` (`empresaProveedoraID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Vehiculo` 
 ADD CONSTRAINT `FK_Vehiculo_PaqueteTuristico`
	FOREIGN KEY (`paqueteTuristicoID`) REFERENCES `PaqueteTuristico` (`paqueteTuristicoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Vuelo` 
 ADD CONSTRAINT `FK_Vuelo_Avion`
	FOREIGN KEY (`avionID`) REFERENCES `Avion` (`avionID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Vuelo` 
 ADD CONSTRAINT `FK_Vuelo_Oferta`
	FOREIGN KEY (`ofertaID`) REFERENCES `Oferta` (`ofertaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Vuelo` 
 ADD CONSTRAINT `FK_Vuelo_PaqueteTuristico`
	FOREIGN KEY (`paqueteTuristicoID`) REFERENCES `PaqueteTuristico` (`paqueteTuristicoID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 ;
